PRESETS = {
    "pcr": {
        "label": "Conventional PCR",
        "primer_min_size": 18,
        "primer_opt_size": 20,
        "primer_max_size": 25,
        "primer_min_tm": 57.0,
        "primer_opt_tm": 60.0,
        "primer_max_tm": 63.0,
        "primer_min_gc": 35.0,
        "primer_max_gc": 65.0,
        "product_size_range": [[150, 400], [400, 800]],
        "max_self_any": 8.0,
        "max_self_end": 3.0,
        "max_pair_any": 8.0,
        "max_pair_end": 3.0,
        "max_hairpin_tm": 45.0,
    },
    "rtpcr": {
        "label": "RT-PCR",
        "primer_min_size": 18,
        "primer_opt_size": 20,
        "primer_max_size": 25,
        "primer_min_tm": 58.0,
        "primer_opt_tm": 60.0,
        "primer_max_tm": 63.0,
        "primer_min_gc": 40.0,
        "primer_max_gc": 60.0,
        "product_size_range": [[100, 300], [300, 600]],
        "max_self_any": 8.0,
        "max_self_end": 3.0,
        "max_pair_any": 8.0,
        "max_pair_end": 3.0,
        "max_hairpin_tm": 45.0,
    },
    "qpcr": {
        "label": "qPCR",
        "primer_min_size": 18,
        "primer_opt_size": 20,
        "primer_max_size": 24,
        "primer_min_tm": 59.0,
        "primer_opt_tm": 60.5,
        "primer_max_tm": 63.0,
        "primer_min_gc": 40.0,
        "primer_max_gc": 60.0,
        "product_size_range": [[70, 150]],
        "max_self_any": 8.0,
        "max_self_end": 3.0,
        "max_pair_any": 8.0,
        "max_pair_end": 3.0,
        "max_hairpin_tm": 45.0,
    },
    "ddpcr": {
        "label": "ddPCR",
        "primer_min_size": 18,
        "primer_opt_size": 20,
        "primer_max_size": 24,
        "primer_min_tm": 59.0,
        "primer_opt_tm": 60.5,
        "primer_max_tm": 63.0,
        "primer_min_gc": 40.0,
        "primer_max_gc": 60.0,
        "product_size_range": [[70, 200]],
        "max_self_any": 8.0,
        "max_self_end": 3.0,
        "max_pair_any": 8.0,
        "max_pair_end": 3.0,
        "max_hairpin_tm": 45.0,
    },
    "mirna": {
        "label": "miRNA assay",
        "primer_min_size": 18,
        "primer_opt_size": 20,
        "primer_max_size": 24,
        "primer_min_tm": 58.0,
        "primer_opt_tm": 60.0,
        "primer_max_tm": 63.0,
        "primer_min_gc": 30.0,
        "primer_max_gc": 65.0,
        "product_size_range": [[60, 120]],
        "max_self_any": 8.0,
        "max_self_end": 3.0,
        "max_pair_any": 8.0,
        "max_pair_end": 3.0,
        "max_hairpin_tm": 45.0,
    },
}
